---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello Woooorld!" 
      
  - name: Create an insecure file
    file:
      path: /tmp/temp.txt
      owner: root
      group: root
      mode: '1777'
      state: touch
      
