---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server mit Variable
    debug:
      msg: "Hello {{var_test_1}}!"
      
  - name: Create a file
    file:
      path: /tmp/temp.txt
      state: touch
      
  - name: Create a folder
    file:
      path: /tmp/ordner_1
      state: directory
  
  - name: Create a folder
    file:
      path: /tmp/ordner_1
      state: directory  
  - name: loop
    debug:
      msg: "Hello {{ item }}"
    loop:
        - Alice
        - Bob
